---

- hosts: localhost
  become: yes
  become_method: sudo

  tasks:
    - name: "Update system"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: "Upgrade system"
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true

    - name: "Install packages"
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: "Docker GPG apt Key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Docker Repository"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: "Install docker"
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: "Launching docker"
      service:
        name: docker
        state: started
        enabled: yes
